### ISSUE TITLE
Not enough free memory to build TRT engine

### ISSUE THREAD

**Issue by kaalen** [NVIDIA/trt-llm-rag-windows#15]
Hi,

I want to check if anyone has been able to complete the pre-requisites and run this reference app on GTX 4070 Ti?

I get stuck on building the TRT engine step with the following error:
`Requested amount of GPU memory (1024 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.`

I opened an issue [issues/1045](https://github.com/NVIDIA/TensorRT-LLM/issues/1045) on TensorRT-LLM repo with more detailed info on my system configuration and repro steps.

I tried playing with different --max_input_len and --max_output_len values, reducing to 512, but that doesn't make any difference. I also tried following the same process but using the smaller model Llama-2-7b, which I theoretically understand should require much less dedicated GPU memory. However, I run into the exact same memory issue.

I would appreciate any suggestions on how to proceed and get this reference app running

**Comment by hanikhatib** [comment]
I’m getting the exact same error with a 4060ti 16GB and 64GB RAM on the CPU.

**Comment by kaalen** [comment]
Glad to hear I'm not the only one. This was really doing my head in and I probably spent 4+ hours trying to find a solution but alas I'm a little out of my depth with NVIDIA frameworks and APIss

**Comment by anujj** [comment]
which trt version are you using? model.pt is only compatible with trt-llm 0.5v

**Comment by anujj** [comment]
Can you please try the updated readme: https://github.com/NVIDIA/ChatRTX/blob/release/0.3/README.md to setup the application.

mistral model is expected to work of all the 30X and 40x GPUs with 8gb and above vmem
