### ISSUE TITLE
Incorrect instructions to build TRT engine

### ISSUE THREAD

**Issue by t3b4n** [NVIDIA/trt-llm-rag-windows#16]
README.md indicates, quote:

> Clone the [TensorRT LLM](https://github.com/NVIDIA/TensorRT-LLM/) repository:
> git clone https://github.com/NVIDIA/TensorRT-LLM.git
> Navigate to the examples\llama directory and run the following script:
> python build.py --model_dir <path to llama13_chat model>...

These instructions are incorrect, there's no "build.py" file inside examples\llama\

Could you please correct the instructions to be able to generate the engine?

**Comment by sarashs** [comment]
I have the same problem. It seems that this repo is badly outdated trt-llm has significantly changed since when they made this. I spent hours on the same issue. You should be following these examples: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/README.md

but even then I still could not create an engine. It seems that the parameters and their names have also changed...

**Comment by ewandel** [comment]
Same here. Useful instructions would be .... useful.

**Comment by sarashs** [comment]
Ok I figured what my problem was. I wasn't using the correct branch. Have you guys been using the rel branch?
if you actually checkout that branch then build.py is there and it works and creates the engine:

git clone --branch rel https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive

**Comment by synacktraa** [comment]
> Ok I figured what my problem was. I wasn't using the correct branch. Have you guys been using the rel branch? if you actually checkout that branch then build.py is there and it works and creates the engine:
> 
> git clone --branch rel https://github.com/NVIDIA/TensorRT-LLM.git cd TensorRT-LLM git submodule update --init --recursive

Thanks so much!

**Comment by vainsoftgames** [comment]
OMG! Thanks! Didn't see anywhere in the instructions that I needed to use the rel branch.

**Comment by NMGibson** [comment]
I am still facing this issue even after making sure I was on the release branch. I keep getting a: 

`C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'C:\\Users\\Administrator\\TensorRT\\TensorRT-LLM\\build.py': [Errno 2] No such file or directory`

I don't know what I am doing wrong. I did the instructions that Sarashs did and then reinputed the python build.py command line. Is there something else I am missing?

**Comment by synacktraa** [comment]
> I am still facing this issue even after making sure I was on the release branch. I keep getting a:
> 
> `C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'C:\\Users\\Administrator\\TensorRT\\TensorRT-LLM\\build.py': [Errno 2] No such file or directory`
> 
> I don't know what I am doing wrong. I did the instructions that Sarashs did and then reinputed the python build.py command line. Is there something else I am missing?

navigate to the examples\llama directory before running build.py

**Comment by anujj** [comment]
Please use latest version and use the updated readme file : https://github.com/NVIDIA/ChatRTX/blob/release/0.3/README.md
