### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index'

### ISSUE THREAD

**Issue by if-ai** [NVIDIA/trt-llm-rag-windows#20]
ModuleNotFoundError: No module named 'llama_index'

```
Environment path found: G:\Chat_RTX\env_nvd_rag
App running with config
 {
    "models": {
        "supported": [
            {
                "name": "Mistral 7B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\mistral\\mistral7b_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\mistral\\mistral7b_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 7168,
                    "temperature": 0.1
                }
            },
            {
                "name": "Llama 2 13B int4",
                "installed": true,
                "metadata": {
                    "model_path": "model\\llama\\llama13_int4_engine",
                    "engine": "llama_float16_tp1_rank0.engine",
                    "tokenizer_path": "model\\llama\\llama13_hf",
                    "max_new_tokens": 1024,
                    "max_input_token": 3900,
                    "temperature": 0.1
                }
            }
        ],
        "selected": "Mistral 7B int4"
    },
    "sample_questions": [
        {
            "query": "How does NVIDIA ACE generate emotional responses?"
        },
        {
            "query": "What is Portal prelude RTX?"
        },
        {
            "query": "What is important about Half Life 2 RTX?"
        },
        {
            "query": "When is the launch date for Ratchet & Clank: Rift Apart on PC?"
        }
    ],
    "dataset": {
        "sources": [
            "directory",
            "youtube",
            "nodataset"
        ],
        "selected": "directory",
        "path": "dataset",
        "isRelative": true
    },
    "strings": {
        "directory": "Folder Path",
        "youtube": "YouTube URL",
        "nodataset": "AI model default"
    }
}
Traceback (most recent call last):
  File "G:\Chat_RTX\RAG\trt-llm-rag-windows-main\app.py", line 28, in <module>
    from trt_llama_api import TrtLlmAPI
  File "G:\Chat_RTX\RAG\trt-llm-rag-windows-main\trt_llama_api.py", line 23, in <module>
    from llama_index.bridge.pydantic import Field, PrivateAttr
ModuleNotFoundError: No module named 'llama_index'
Press any key to continue . . .
```

2x 3090 windows 10. Went onto went into `cd C:\Users\<USER>\AppData\Local\NVIDIA\MiniConda\Scripts`  and  `conda activate G:\Chat_RTX\env_nvd_rag `  `pip install -U llama_index` same error popped up

**Comment by if-ai** [comment]
version ChatWithRTX_Offline_2_11_mistral_Llama

**Comment by kawanet** [comment]
same error on 3080 Ti Windows 11

**Comment by BLSharda** [comment]
@if-ai , can you confirm if there is space in your windows user name? Asking since we identified issues with path with spaces.

` C:\Users\<USER>\AppData\Local\NVIDIA\MiniConda\Scripts `

**Comment by kawanet** [comment]
@BLSharda In my case, my username does NOT have a white space ` ` but has a hyphen `-` instead.

**Comment by azureatlas** [comment]
Same on RTX 4070 Ti, Windows 11 and NO spaces or dashes in

```
C:\Users\<USER>\AppData\Local\NVIDIA\MiniConda\Scripts
```

**Comment by anthonyda** [comment]
Same on 4070, no space on username, path is `C:\Users\antho\AppData\Local\NVIDIA\MiniConda\Scripts` with 551.52 drivers on Windows 11 23H2.

**Comment by if-ai** [comment]
> @if-ai , can you confirm if there is space in your windows user name? Asking since we identified issues with path with spaces.
> 
> `C:\Users\<USER>\AppData\Local\NVIDIA\MiniConda\Scripts`

there is no space or symbols in my username just normal camelcase latin alphabet letters I activate the env in conda `C:\Windows\system32>conda activate C:\Users\NvdiaUser\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag ` installed the reqs 
`(C:\Users\NvdiaUser\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag) C:\Windows\system32>pip install -r "C:\Users\NvdiaUser\AppData\Local\NVIDIA\ChatWithRTX\RAG\trt-llm-rag-windows-main\requirements.txt"` got some issue with grpcio WARNING: No metadata found in `c:\users\nvdiauser\appdata\roaming\python\python310\site-packages` went to the folder manually removed the package and inastalled it again with `pip install --force-reinstall --no-deps grpcio==1.48.1` confirmed it installed without error Started ChatWithRTX got again the message there is not LLama_Index module which is a called from `\ChatWithRTX\RAG\trt-llm-rag-windows-main\app.py` or `ChatWithRTX\RAG\trt-llm-rag-windows-main\trt_llama_api.py` try  installing just llama index` pip install llama-index==0.9.27` it again same message notice site package on the env was missing some folders like bridge inside the llama_index meaning probably got corrupted because I had the ChatwithRTX open to read the log error message Not sure if true but is my wild guess so I deleted the corrupted folder llama_index and and dist info manually and pip installed it again By the way I also added `C:\Users\NvidiaUser\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\Lib\site-packages\llama_index` and `C:\Users\NvidiaUser\AppData\Local\NVIDIA\MiniConda\Lib\site-packages\llama_index` to my global and user environment variables on windows and then did a final `pip install llama-index==0.9.27` and bang it works now https://i.imgur.com/RZ3zsc8.png

**Comment by if-ai** [comment]
I think I will close this since I found the solution posted above. I Tested the embedings are working too.
