### ISSUE TITLE
Fine-tune WhereIsAI/UAE-Large-V1 embeddings for Models First ?

### ISSUE THREAD

**Issue by sergiosolorzano** [NVIDIA/trt-llm-rag-windows#23]
Hi, 

The embeddings model used on default ChatRTX installation is [WhereIsAI/UAE-Large-V1](https://github.com/SeanLee97/AnglE). To use the generated embeddings in an LLM model imported to ChatRTX, do I first need to fine tune a pre-trained LLM model with [AnglE](https://github.com/SeanLee97/AnglE?tab=readme-ov-file#angle-llama)  so that WhereIsAI/UAE-Large-V1 embeddings are compatible with an LLM? e.g.

`angle = AnglE.from_pretrained('NousResearch/Llama-2-7b-hf', pretrained_lora_path='SeanLee97/angle-llama-7b-nli-v2')`

Thank you !

**Comment by anujj** [comment]
NO fine tuning is required
