### ISSUE TITLE
I am building a software like this right now, and finding this is depressing

### ISSUE THREAD

**Issue by ludiusvox** [NVIDIA/trt-llm-rag-windows#25]
I have an enthusiast project I am working on right now with Omdena AI that essentially operates identical to this software.  I was never looking for compensation or anything.  I planned on building a freeware that any developer can use.  You guys just cranked it out when I was doing project proposals.   Now that I am week 3 in the project I find this.  And I am upset.  My only consolation is that you published it faster than I did because you guys are so rich you can pay 1000's of developers.

My only concern about your guys code, is that it's a black-box, and not a white box.  I am leaving all my code open, as well as documentation how to tweak every fine detail.  And make it easier to install than this.

I don't think all these GUI's are necessary.  We just doing a streamlit UI that any developer can come along and put into their own game, we use RAG, and "in character" speech, and all these context tweaks and everything.  It's really coming along well.  But I feel bad now.

Have a nice day.

**Comment by cloudrage999** [comment]
man what you are complaining about ?..first i should say there are a lot of open source rag projects much accurate than this software like privategpt and quivr
second if you have sth that works,it will find its users
so dont complain

**Comment by ludiusvox** [comment]
ok

**Comment by mr-pepe69** [comment]
i will be interested if you get it working as a installer and a simple API to infere with either locally or over https. because i tried with this and it is being hell. differentiate from others, improve where others ignore or fail.

**Comment by computersrmyfriends** [comment]
@ludiusvox , I think the reasoning provided by @cloudrage999 is reasonable. There are already tools out there. ChatRTX isn't the first tool, isn't the best yet and I really honestly don't understand the purpose and where they're going with this when there are feature rich and more user-friendly tools around (especially LM Studio, Anything LLM for RAG, APIs). Standarized ones like Ollama for the console.

My curiosity is about if this whole tool is just for NVIDIA's name's sake or is there a really valid problem to solve for this tool?

**Comment by ludiusvox** [comment]
That's what I ended up doing in my implementation, I piggyback my project off of LM studio with FAISS RAG and it worked great with Mistral.

**Comment by anujj** [comment]
The updated version is release with mode model support. Please try 0.3 branch.
