### ISSUE TITLE
invalid session error

### ISSUE THREAD

**Issue by YeisonHunt** [NVIDIA/trt-llm-rag-windows#32]
After a normal installation,

I tried to open the program, just automatically after setup because i wasn't able to find any installed program or command or a shorcut to run it (another huge enhance opportunity there), the program on browser throws `invalid session` even with cognito mode on different browsers.

Tested on windows 11. 
Rtx 3080 
Ram 64 gb

**Comment by noahc1510** [comment]
The app generated a cookie and it's missing from the URL, you should add it. Otherwise, an invalid session error will be reported.

**Comment by YeisonHunt** [comment]
> The app generated a cookie and it's missing from the URL, you should add it. Otherwise, an invalid session error will be reported.

Where should I take that cookie ? From terminal ? Or ?

**Comment by noahc1510** [comment]
Yes, it's from the terminal like this: Open http://127.0.0.1:3096?cookie=foo-bar&__theme=dark in browser to start Chat with RTX

**Comment by anujj** [comment]
after starting the application, you can copy the url that has the cookies value to the browser to run it
