### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_llm'

### ISSUE THREAD

**Issue by ryletd** [NVIDIA/trt-llm-rag-windows#34]
Hello, after installing and running Chat with RTX I get error `ModuleNotFoundError: No module named 'tensorrt_llm'`. How to fix it?

<img width="665" alt="Screenshot_2" src="https://github.com/NVIDIA/trt-llm-rag-windows/assets/84879606/6cc2739d-2c88-4d54-b236-650ded67d11f">

**Comment by noahc1510** [comment]
I tried `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm` this command to fix it.

**Comment by josedaesbar** [comment]
> I tried `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm` this command to fix it.

It doesn't work for me 😢 
![Captura de pantalla 2024-01-29 112432](https://github.com/NVIDIA/trt-llm-rag-windows/assets/67618319/d579a810-9438-4e8e-830d-0cc1278853be)

**Comment by josedaesbar** [comment]
> I tried `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm` this command to fix it.

It didn't work for me 😞 
![Captura de pantalla 2024-02-19 144718](https://github.com/NVIDIA/trt-llm-rag-windows/assets/67618319/508a354d-c82f-4ca7-a9d0-e6b7076ab0ac)

**Comment by kedarpotdar-nv** [comment]
@ryletd Can you please try a fresh install and report back?

**Comment by anujj** [comment]
Please try with the branch release/0.3 and follow the instructions
