### ISSUE TITLE
ChatWithRTX Installer is corrupt.

### ISSUE THREAD

**Issue by fcodes0** [NVIDIA/trt-llm-rag-windows#42]
Sorry if this isn't the correct place to post this but I don't know where else to notify the dev team about this. The zip file containing the prebuilt installer from Nvidia's web page (https://www.nvidia.com/en-us/ai-on-rtx/chat-with-rtx-generative-ai/) is corrput. Myself and others have tried downloading the zip file multiple times and it still errors out saying that the file is corrupt.

theres a whole reddit thread with others having the same issue. https://www.reddit.com/r/ChatWithRTX/comments/1avw4vn/corrupt_zip_file/

**Comment by datkat21** [comment]
Can repro, tried downloading a few times and it was corrupted and missing crucial files. A workaround I found while digging around Reddit was to install the [demo version](https://us.download.nvidia.com/RTX/NVIDIA_ChatWithRTX_Demo.zip) which seems to work for me

**Comment by tr7zw** [comment]
With 7zip you can open the zip, but one of the model files in it is corrupted(fails to unzip correctly) and there seems to be a bunch of files missing(only executable file is miniconda, no python files at all).

**Comment by anujj** [comment]
Can you try the latest package please
