### ISSUE TITLE
build TRT engine fail

### ISSUE THREAD

**Issue by petersha0630** [NVIDIA/trt-llm-rag-windows#43]
Loading weights from groupwise AWQ LLaMA checkpoint...
Traceback (most recent call last): 
  File "C:\Users\peter\TensorRT-LLM\examples\llama\build.py", line 906, in <module>
    build(0, args)
  File "C:\Users\peter\TensorRT-LLM\examples\llama\build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "C:\Users\peter\TensorRT-LLM\examples\llama\build.py", line 665, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "C:\Users\peter\TensorRT-LLM\examples\llama\weight.py", line 1433, in load_from_awq_llama
    assert False, "Unsupported AWQ quantized checkpoint format"
AssertionError: Unsupported AWQ quantized checkpoint format

model.pt was download from https://catalog.ngc.nvidia.com/orgs/nvidia/models/llama2-13b/files?version=1.2

**Comment by bestcarly** [comment]
I have same problem.

**Comment by kedarpotdar-nv** [comment]
Hi @petersha0630, can you share the trt-llm version you are working with?

**Comment by petersha0630** [comment]
> Hi @petersha0630, can you share the trt-llm version you are working with?

TensorRT-LLM-0.7.0

**Comment by raymondbernard** [comment]
Make sure you guys are using the full path to the checkpoint plus the file name such as : python build.py --model_dir C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\TensorRT-LLM-0.7.0\examples\llama\model\codellama13b_hf --quant_ckpt_path C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\TensorRT-LLM-0.7.0\examples\llama\model\codellama13b_w\llama_tp1_rank0.npz --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha  --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --per_group --output_dir C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\Tens
orRT-LLM-0.7.0\examples\llama\model\engine

**Comment by petersha0630** [comment]
thank you for help

> Make sure you guys are using the full path to the checkpoint plus the file name such as : python build.py --model_dir C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\TensorRT-LLM-0.7.0\examples\llama\model\codellama13b_hf --quant_ckpt_path C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\TensorRT-LLM-0.7.0\examples\llama\model\codellama13b_w\llama_tp1_rank0.npz --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --per_group --output_dir C:\Users\RayBe\OneDrive\Documents\nvidiaplayground\Tens orRT-LLM-0.7.0\examples\llama\model\engine

thank you for help

**Comment by elikakohen** [comment]
` --enable_context_fmha`  Did the trick for me.

`python build.py --model_dir E:\Dev\NVIDIA\TensorRT-LLM\examples\llama\llama2-13b\Llama2-13b-chat-hf\ --quant_ckpt_path E:\Dev\NVIDIA\TensorRT-LLM\examples\llama\llama2-13b\llama2-13b_v1.4\llama_tp1_rank0.npz --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16  --enable_context_fmha --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --per_group --enable_context_fmha --max_batch_size 1 --max_input_len 3000 --max_output_len 1024 --output_dir E:\Dev\NVIDIA\TensorRT-LLM\examples\llama\llama2-13b\Engine\
`
