### ISSUE TITLE
[TensorRT-LLM][ERROR] CUDA runtime error in cudaDeviceGetDefaultMemPool

### ISSUE THREAD

**Issue by jordiyeh** [NVIDIA/trt-llm-rag-windows#49]
When running NVIDIA Chat with RTX, I get the following error

RuntimeError: [TensorRT-LLM] [ERROR] CUDA runtime error in cudaDeviceGetDefaultMemPool(&memPool, device): operation not s upported (C: \Users\tejaswinp\workspace\tekit\cpp\tensorrt_llm\runtime\bufferManager.cpp:171)

![image](https://github.com/NVIDIA/trt-llm-rag-windows/assets/5520251/775950d6-3bdf-45d0-83ef-38879622b11e)

Windows 11 Pro with 16GB RAM with NVIDIA A-40-16Q running in a VM environment.

Let me know what else can I provide to help with troubleshooting.

**Comment by renareke** [comment]
Same issue here...

**Comment by anujj** [comment]
Hey .. can you please try this in native windows without VM environment .. we have seen this same issue on VM machines and VGPUs. They are not supportive
