### ISSUE TITLE
How to switch language?!

### ISSUE THREAD

**Issue by andresg97** [NVIDIA/trt-llm-rag-windows#53]
I want to get responses in spanish, not in english!!!!! Why is the app advertised in spanish when it only runs in english and there are no instructions on how to change it??!

**Comment by anujj** [comment]
Spanish is not supported

**Comment by anujj** [comment]
also could you please let me know where the app is advertised in Spanish

**Comment by andresg97** [comment]
https://www.nvidia.com/es-es/ai-on-rtx/chatrtx/

Descargar ChatRTX de NVIDIA
Simplemente descarga, instala y empieza a chatear de inmediato.

¿Qué es ChatRTX?
ChatRTX es una aplicación de demostración que te permite personalizar un modelo de lenguaje de gran tamaño (LLM) GPT conectado a tu propio contenido: documentos, notas, vídeos u otros datos. Al aprovechar [la generación aumentada por recuperación (RAG)](https://blogs.nvidia.com/blog/what-is-retrieval-augmented-generation/), [TensorRT-LLM](https://developer.nvidia.com/blog/nvidia-tensorrt-llm-supercharges-large-language-model-inference-on-nvidia-h100-gpus/) y la aceleración RTX, puedes consultar un chatbot personalizado para obtener respuestas contextualmente relevantes con rapidez. Como todo se ejecuta localmente en tu PC o estación de trabajo Windows RTX, obtendrás resultados rápidos y seguros.


Chatea con tus archivos
ChatRTX admite varios formatos de archivo, incluidos texto, pdf, doc/docx y xml. Solo tienes que seleccionar la aplicación en la carpeta que contiene los archivos y se cargarán en la biblioteca en cuestión de segundos.


Next time put a big disclaimer or something, it's a big waste of time installing windows 11 and downloading 40 gb to be disappointed.
