### ISSUE TITLE
What version of Cuda is needed?

### ISSUE THREAD

**Issue by leandroMsouza** [NVIDIA/trt-llm-rag-windows#54]
I'm trying to run with the engine (llama_float16_tp1_rank0.engine)

but I'm getting this error

![1](https://github.com/NVIDIA/trt-llm-rag-windows/assets/6230936/ec888a6c-0f47-45b3-b814-7d43192edaee)

**Comment by anujj** [comment]
Have do done the installation thought the installer released by nvidia ? or you are doing manual setup ?

**Comment by leandroMsouza** [comment]
by Nvidia Installer

**Comment by anujj** [comment]
Could you please translate the error in English for better understanding. We have not seen any error from our side related to this this dll form our side

**Comment by thiagojramos** [comment]
> Could you please translate the error in English for better understanding. We have not seen any error from our side related to this this dll form our side

I stumbled upon this by chance, but to not leave it unanswered, here's what the error message says in English:

```shell
Failed to locate the entry point for the 
procedure 
?destroyTensorDescriptorExOps@cudaNN@@YA?AW4cudnnStatus_t@@PEAPEAUcudnnTensorStruct@@@Z in the 
dynamic link library C:\Program Files\Python310\Lib\site-packages\nvidia\cudnn\bin\cudnn_adv_infer64_8.dll.
``` 

**And to answer the question:** 

it's probably an error with the CUDA/CuDNN library installation or a version mismatch between the CUDA, CuDNN, and PyTorch/TensorFlow

**Comment by leandroMsouza** [comment]
Thanks, I'll re-install everything
