### ISSUE TITLE
'trtllm-build' is not recognized

### ISSUE THREAD

**Issue by ethorpe** [NVIDIA/trt-llm-rag-windows#58]
Hello,

     I am trying to run this command below but I get the  error 'trtllm-build' is not recognized. I noticed that 'trtllm-build' build script is not even in the branch. Are the instructions wrong? Can someone help me resolve this error and find out how to get 'trtllm-build'? Thanks in advance. 

Full Command:
trtllm-build --checkpoint_dir .\model\mistral_model\model_checkpoints --output_dir .\model\mistral_model\engine --gpt_attention_plugin float16 --gemm_plugin float16 --max_batch_size 1 --max_input_len 7168 --max_output_len 1024 --context_fmha=enable --paged_kv_cache=disable --remove_input_padding=disable

**Comment by anujj** [comment]
@ethorpe  Have you installed the trt-llm wheel from: https://github.com/NVIDIA/ChatRTX/tree/release/0.3/wheel?After the wheel installation, trtllm-build should be present in the Python environment in the Scripts folder. Consider adding the Scripts folder to the environment path.
