### ISSUE TITLE
⁉️ Benefit of using ChatRTX instead of LMStudio or Ollama and other similar tools❓❔

### ISSUE THREAD

**Issue by computersrmyfriends** [NVIDIA/trt-llm-rag-windows#59]
Hello,
I'd like to genuinely understand the purpose and difference between using this vs the alternate tools like Ollama, BigAGI and Anything LLM that also have RAG, Inference, etc.

Don't they also use the same NVIDIA drivers? What is the benefit of developing ChatRTX?

If I need to do inference on any of the models, should I use ollama or ChatRTX? Does ChatRTX use any specific additional feature of the NVIDIA GPUs that the other tools can't use or don't have access to? 

Thanks

**Comment by anujj** [comment]
The goal of this application is to foster the AI ecosystem on edge devices. How it is different from other applications is that it uses the TensorRT-LLM inference backend: https://developer.nvidia.com/tensorrt#inference

**Comment by computersrmyfriends** [comment]
Thanks, that makes sense.
