### ISSUE TITLE
Unable to build from source due to missing dependency

### ISSUE THREAD

**Issue by metiscus** [NVIDIA/trt-llm-rag-windows#72]
Hello,

I am following along with the readme and when I get to Step 4.
`Download 'ngcsdk-3.41.2-py3-none-any.whl' from [here](https://catalog.canary.ngc.nvidia.com/orgs/nvidia/teams/ngc-apps/resources/ngc_sdk/files?version=3.41.2) and install it using the command below. This enables us to downloads from NGC:`

The linked URL appears to be down. Additionally, version 3.41.2 does not appear in pip and the other available versions cause a dependency issue around the langchain-core - packaging dependency.

`langchain-core 0.1.52 requires packaging<24.0,>=23.2,`

The executable installer results in a functional system but the source can't be made to work until this is resolved. I am hoping that the folks who run this have a way to get in touch with the hosts of the package and get the system back online. If this turns out to be a temporary system outage, I apologize for bothering you.

**Comment by lucasmarzetti** [comment]
Hello I have the same issue, any update?

**Comment by anujj** [comment]
Link is active now. https://catalog.canary.ngc.nvidia.com/orgs/nvidia/teams/ngc-apps/resources/ngc_sdk/files?version=3.41.2

**Comment by Maxime-LP5** [comment]
Hi, thanks for sharing your work but I still have the same issue with the site being offline

**Comment by lucasmarzetti** [comment]
same here

**Comment by timur-losev-bplay** [comment]
same

**Comment by timur-losev-bplay** [comment]
Try this one
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/ngc-apps/resources/ngc_sdk/files?version=3.41.2

**Comment by gustavozantut** [comment]
> Try this one https://catalog.ngc.nvidia.com/orgs/nvidia/teams/ngc-apps/resources/ngc_sdk/files?version=3.41.2

i am having some error with the file in this link, anyone?
```
>>pip install .\ngcsdk-3.41.2-py3-none-any.whl
Processing c:\users\gusta\trt-llm-rag-windows\chatrtx_apis\dist\ngcsdk-3.41.2-py3-none-any.whl
ERROR: Wheel 'ngcsdk' located at C:\Users\gusta\trt-llm-rag-windows\ChatRTX_APIs\dist\ngcsdk-3.41.2-py3-none-any.whl is invalid.
```
