### ISSUE TITLE
Remote/shared link/ shared session do not allow for reference files opening

### ISSUE THREAD

**Issue by ttrandynamic** [NVIDIA/trt-llm-rag-windows#76]
When i access my chatrtx remotely, I can not open the reference link, the file would be open on my home computer where the chatrtx is running.

is there a way I can modify the code for the reference file to be a download from my home computer if I dont have access to the file location?

**Comment by anujj** [comment]
This request is not support currently. You can modify the code in the app.py file where you are running chatrtx

**Comment by Luoyangs** [comment]
You can use Flask to independently produce a file service, for example
```
from flask import Flask, send_from_directory
...
    def __init__(self, chatbot=None, streaming = False) -> None:
        self._interface = None
        self._query_handler = chatbot
        self._streaming = streaming
        self.config = Configuration()
        self._dataset_path = self._get_dataset_path()
        self._default_dataset_path = self._get_default_dataset_path()
        self._default_chinese_dataset_path = self._get_default_chinese_dataset_path()
        self._default_clip_dataset_path = self._get_default_clip_dataset_path()
        self._init_static()
        pass

    def _init_static(self):
        app = Flask(__name__, static_folder=self._dataset_path)
        

        @app.route('/file/<path:filename>')
        def serve_file(filename):
            return send_from_directory(self._dataset_path, filename)
        
        def run_flask():
            app.run(port=5000, host=SERVER_HOST)

        # 在单独的线程中启动 Flask 应用
        threading.Thread(target=run_flask).start()
```
then you can use a link like this:
```
file_path = f"http://{SERVER_HOST}:5000/file/{file_name}"
file_link = f'<a data-link="{file_path}" href="{file_path}">{file_name}</a>'
```

**Comment by ttrandynamic** [comment]
thank you for the tip, but i'm not a coder by profession. editing the app.py gets me these errors.
![image](https://github.com/NVIDIA/ChatRTX/assets/173515910/3a24f11a-89f5-4184-a431-ac7a32774315)

These two lines below going somewhere in the user_interface.py?
file_path = f"http://{SERVER_HOST}:5000/file/{file_name}"
file_link = f'<a data-link="{file_path}" href="{file_path}">{file_name}</a>'

Am i replacing the server_host and port with my own?

mine is currently running on //127.0.0.1:8443.

thank you for very much for all the help!

**Comment by Luoyangs** [comment]
right, the function _init_static defined in user_interface.py , then called by __init__(exist init function in user_interface.py), after this ,you can use the static file service in app.py

SERVER_HOST is your computer ip which run the chatRTX, like 192.168.2.10, don't use 127.0.0.1
the port is a random number you like

**Comment by tpc2233** [comment]
> When i access my chatrtx remotely, I can not open the reference link, the file would be open on my home computer where the chatrtx is running.
> 
> is there a way I can modify the code for the reference file to be a download from my home computer if I dont have access to the file location?

Are you able to run gradio remote just by adding the cookie in the end or had to do anything else? Thank you!

**Comment by ttrandynamic** [comment]
tpc2233, i replied to your issue post.
