### ISSUE TITLE
No interface is running right now

### ISSUE THREAD

**Issue by tpc2233** [NVIDIA/trt-llm-rag-windows#78]
Tried everything but already get that issue on Gradio when running public.

My steps:

Taking Running on public URL: https://14aef643650a6a12b7.gradio.live

And adding the cookie from local adress, get like this:
URL: https://14aef643650a6a12b7.gradio.live?cookie=968c52c4-16d6-4a44-97d4-9375490c82a9&__theme=dark 

But still no luck everytime. 
Running on 0.3

Thank You!

**Comment by ttrandynamic** [comment]
![image](https://github.com/NVIDIA/ChatRTX/assets/173515910/b60b3c71-0bbe-41ef-8f56-d5794f8b7db7)
follow this gentlemen's solution. it will work.

**Comment by tpc2233** [comment]
> ![image](https://private-user-images.githubusercontent.com/173515910/344425992-b60b3c71-0bbe-41ef-8f56-d5794f8b7db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2OTAwMjQsIm5iZiI6MTcxOTY4OTcyNCwicGF0aCI6Ii8xNzM1MTU5MTAvMzQ0NDI1OTkyLWI2MGIzYzcxLTBiYmUtNDFlZi04ZjU2LWQ1Nzk0ZjhiN2RiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxOTM1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTViZmI0YTE5NzkwZWQ2MTFjNjE4YTQwNTNkOTk1YThkOGFmMjJmOWQwOWYyYmNlNTA3Y2RiNmViMzEwYzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yyJzNCY90A66_5BZ5fv-T2S86IqCHgGNArAg7THW3x0) follow this gentlemen's solution. it will work.

Worked PERFECT, Thank you so much
