### ISSUE TITLE
Instalation failed

### ISSUE THREAD

**Issue by Ericlebose** [NVIDIA/trt-llm-rag-windows#86]
When I install chat rtx version 0.4 it says"an error has occured while setting up data directory"
![Capture d'écran 2024-08-10 180835](https://github.com/user-attachments/assets/d01351a4-4377-4d9f-9c8d-e873660d666e)
While installing the 0.2.1 version it is all fine

**Comment by gustavozantut** [comment]
solution: https://forums.developer.nvidia.com/t/bug-chatrtx-installer-error-on-non-english-versions-of-windows/302396

**Comment by Ericlebose** [comment]
Thank you so muchEnvoyé depuis mon téléphone-------- Message original --------De : Gustavo Abbomerato Zantut ***@***.***>Date : dim. 11 août 2024 à 17:43À : NVIDIA/ChatRTX ***@***.***>Cc : Ericlebose ***@***.***>, Author ***@***.***>Objet : Re: [NVIDIA/ChatRTX] Instalation failed (Issue #86)
solution: https://forums.developer.nvidia.com/t/bug-chatrtx-installer-error-on-non-english-versions-of-windows/302396

**Comment by NEVARLeVrai** [comment]
hey i dont have the .nvi file ? still facing the issue

**Comment by Day-fit** [comment]
For anyone still facing the issue, the .nvi file is located in C:\Users\<username>\AppData\Local\Temp\ChatRTXInstaller\ChatRTX.

**Comment by jrausch12** [comment]
The solution suggested above did not work for me. I'm on an English edition of Windows 11.

**Comment by Veniman8000** [comment]
Why not add a workaround into the installer? This is just inconvenient and prevents me from installing ChatRTX as well...

**Comment by jrausch12** [comment]
Use AnythingLLM. It's much better than this poor excuse for a local LLM interface.
