### ISSUE TITLE
infinite loading screen.

### ISSUE THREAD

**Issue by 111100001** [NVIDIA/trt-llm-rag-windows#90]
i reinstalled multiple times and that didn't fix it.
someone on reddit comments reported the same issue (op is me)

![image](https://github.com/user-attachments/assets/79900a81-dc1b-4727-aa00-6b33ce3c7541)

![image](https://github.com/user-attachments/assets/54d69946-e271-47d1-ba14-2dac2d683e5d)

**Comment by sueyda** [comment]
![resim_2024-08-26_162743606](https://github.com/user-attachments/assets/dca31900-d33a-494f-a734-af4b5d28503b)
same problem very annoying.

**Comment by anujj** [comment]
Can you please launch the 'Nvidia chatrtx.exe' from cmd and share me the cmd logs
the exe is located at: C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked

**Comment by anujj** [comment]
are you installing though the NvAPP ?

**Comment by sueyda** [comment]
yes

**Comment by spacevini8** [comment]
yea I have the exact same issue

**Comment by 111100001** [comment]
UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode)  `python3 app_launch.py` and i got an error that said no module named win32process was found

i looked it up and found similar issue in another software but the solution was to install  `pypiwin32` using `pip `and tried running the app again and it worked

`pip install -U pypiwin32`

**Comment by spacevini8** [comment]
still not working for me

edit: nope, it's working, thanks bro.

**Comment by drandarov-io** [comment]
> UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> 
> i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> 
> `pip install -U pypiwin32`

@111100001 I don't think this issue should be closes. While you found a workaround/the underlying cause, this is still an issue with the default installation.

**Comment by HappyDoubleG** [comment]
> UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> 
> i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> 
> `pip install -U pypiwin32`

Didn't work for me.
I'm still stuck on loading screen.

**Comment by drandarov-io** [comment]
> > UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> > i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> > `pip install -U pypiwin32`
> 
> Didn't work for me. I'm still stuck on loading screen.

In addition to installing the depencency, try running the application as administrator.

**Comment by HappyDoubleG** [comment]
> > > UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> > > i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> > > `pip install -U pypiwin32`
> > 
> > 
> > Didn't work for me. I'm still stuck on loading screen.
> 
> In addition to installing the depencency, try running the application as administrator.

Didn't work.

**Comment by MegaMind2999** [comment]
### The error in my case is:
22:52:26.958 > Error while loading C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py *** PY ***  Python Error  Call to 'fileImport' failed:
>         chatbot = await python(pyfile)
  at async initializeChatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:33:19)
  at async initializeBridgeCommands (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\index.js:21:18)

... across the bridge ...

> nltk.data.find("tokenizers/punkt")
  at __init__ (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\utils.py:65)
> raise LookupError(resource_not_found)
  at find (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\nltk\data.py:579)
  at exec_module (<frozen importlib._bootstrap_external>:883)
  at _call_with_frames_removed (<frozen importlib._bootstrap>:241)
> from backend import Backend, Mode
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py:33)
> from ChatRTX.chatrtx import ChatRTX
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\backend.py:2)
> from ChatRTX.inference.pytorch.CLIP import ClipInference
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\ChatRTX\chatrtx.py:23)
> from llama_index.core.schema import TextNode
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\ChatRTX\inference\pytorch\CLIP.py:26)
> from llama_index.core.base.response.schema import Response
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\__init__.py:10)
> from llama_index.core.schema import NodeWithScore
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\base\response\schema.py:9)
> from llama_index.core.utils import SAMPLE_TEXT, truncate_text
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\schema.py:18)
> globals_helper = GlobalsHelper()
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\utils.py:89)
> nltk.download("punkt_tab", download_dir=self._nltk_data_dir)
  at __init__ (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\llama_index\core\utils.py:67)
> for msg in self.incr_download(info_or_id, download_dir, force):
  at download (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\nltk\downloader.py:774)
> yield from self._download_package(info, download_dir, force)
  at incr_download (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\nltk\downloader.py:642)
> os.makedirs(os.path.join(download_dir, info.subdir), exist_ok=True)
  at _download_package (C:\Program Files\NVIDIA Corporation\ChatRTX\env_nvd_rag\lib\site-packages\nltk\downloader.py:699)
  at makedirs (os.py:225)
*** JS *** PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\NVIDIA Corporation\\ChatRTX\\env_nvd_rag\\lib\\site-packages\\llama_index\\core\\_static/nltk_cache\\tokenizers'
22:52:26.959 > Error while getting bridge commands TypeError: Cannot read properties of undefined (reading 'ChatBot')
    at new Chatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:79:27)
    at Chatbot.init (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar.unpacked\node_modules\pythonia\src\pythonia\Bridge.js:48:18)
    at initializeChatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:227:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initializeBridgeCommands (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\index.js:21:18)

### I went to that location and didnt find the file "tokenizers"

**Comment by corang** [comment]
Same error here

**Comment by ArturKasymov** [comment]
Once I've started powershell as admin `Nvidia chatrtx.exe` works

**Comment by ETM500** [comment]
Same error, and these word-arounds don't work.

**Comment by anujj** [comment]
@ETM500 : What error you are getting in the cmd ?

**Comment by mrjkey** [comment]
> Once I've started powershell as admin `Nvidia chatrtx.exe` works

This worked for me as well 👍 
For anyone who needs to find the file, here is where mine is:
"C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\NVIDIA ChatRTX.exe"

**Comment by NopeProsOnly** [comment]
Same issue, this should stay open

**Comment by KenzKD** [comment]
> > Once I've started powershell as admin `Nvidia chatrtx.exe` works
> 
> This worked for me as well 👍 For anyone who needs to find the file, here is where mine is: "C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\NVIDIA ChatRTX.exe"

I had the Same issue but at least this worked for me.

**Comment by HondaFit** [comment]
> Once I've started powershell as admin `Nvidia chatrtx.exe` works

This also worked for me as well . A faster way to do this is the following:
Create a Shortcut to NVIDIA ChatRTX

    Locate the Executable:
        Navigate to the folder where NVIDIA ChatRTX.exe is located (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\NVIDIA ChatRTX.exe)

    Create a Shortcut:
        Right-click on NVIDIA ChatRTX.exe.
        Select Create shortcut. This will be made in the desktop

    Set the Shortcut to Run as Administrator:
        Right-click on the shortcut you just created and select Properties.
        Go to the Compatibility tab.
        Check the box that says Run this program as an administrator .
        Click  Apply, and close the properties window.

My shortcut was located in the desktop but yours might vary

**Comment by barisener** [comment]
> UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> 
> i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> 
> `pip install -U pypiwin32`

worked for me.

**Comment by heff09** [comment]
On Windows, navigate to the folder below:

C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked

Right click properties of [NVIDIA ChatRTX.exe] 

Disable Fullscreen Optimisations:

![Image](https://github.com/user-attachments/assets/dc7678b1-182d-4d2f-9276-0c977e7a61f0)

**Comment by mikejhill** [comment]
> UPDATE: i have fixed the issue by launching the app_launch.py from the CMD (admin mode) `python3 app_launch.py` and i got an error that said no module named win32process was found
> 
> i looked it up and found similar issue in another software but the solution was to install `pypiwin32` using `pip `and tried running the app again and it worked
> 
> `pip install -U pypiwin32`

Just installed ChatRTX through NVIDIA App today and ran into the same issue. This was the solution for me. However, it didn't get fixed right away -- it kept spinning, and I ran a few other commands to see if anything worked. It first started working when running `app_launch.bat` as admin, so my best guess is that was the final step.

Running `NVIDIA ChatRTX.exe` as others suggested was not helpful for me. I ran into the same `Error while loading C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py` error as some others. However, running that directly will bypass some things (such as assigning certain permissions to the process), so it doesn't seem surprising that it has issues.

Seems odd that this ticket is closed. Best reproduction of my steps to fix the issue:
1. Open your preferred shell and navigate to the ChatRTX directory.
2. Use NVIDIA's packaged Python to install `pypiwin32`.
3. Run `app_launch.bat` as administrator.

Example in Command Prompt as Administrator (remember: type it out, don't copy):
```batch
cd "C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0"
..\..\env_nvd_rag\Scripts\pip install -U pypiwin32
.\app_launch.bat
```

**Comment by jsanjuan2016** [comment]
Same problem here... For me the solution is to execute the program with administrator rights:
 
```
- Open command (CMD) as Administrator
- Go to "C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked"
- Execute "NVIDIA ChatRTX.exe"
```

**Comment by v1cferr** [comment]
> Once I've started powershell as admin `Nvidia chatrtx.exe` works

It works for me too.

1. Open PowerShell as Admin
2. `cd C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked>`
3. run `'.\NVIDIA ChatRTX.exe'`

![Image](https://github.com/user-attachments/assets/949b945d-f75f-4650-b295-8053163d825c)

**Comment by SmilerRyan** [comment]
Still happens to me. i managed to install pypiwin32 ``..\..\env_nvd_rag\Scripts\pip install -U pypiwin32`` and run ``NVIDIA ChatRTX.exe`` as admin but it still fails. no errors appear to be there but the screen is just black, seems like the models are there but the ui won't load.

```
C:\Users\Ryan\Desktop\ChatRTX\#Installed\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked# "NVIDIA ChatRTX.exe"

19:50:30.157 > systemLanguage
19:50:30.244 > Conda setup done!
19:50:30.381 > C:\Users\Ryan\Desktop\ChatRTX\#Installed\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py
19:50:30.457 > (node:16388) electron: Failed to load URL: file:///C:/Users/Ryan/Desktop/ChatRTX/#Installed\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app\build\index.html with error: ERR_FILE_NOT_FOUND
(Use `NVIDIA ChatRTX --trace-warnings ...` to show where the warning was created)
[16388:1128/195030.459:ERROR:interface_endpoint_client.cc(707)] Message 0 rejected by interface blink.mojom.WidgetHost
[TensorRT-LLM] TensorRT-LLM version: 0.9.0
19:50:37.085 > Loaded python file C:\Users\Ryan\Desktop\ChatRTX\#Installed\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py
19:50:37.234 > [PyE] 2024-11-28 19:50:37,234 - [ChatRTX] - INFO - backend.py:40 - Model init for dir C:\ProgramData\NVIDIA Corporation\chatrtx
Copied contents of C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\ChatRTX\model_manager\../sample_data to C:\ProgramData\NVIDIA Corporation\chatrtx\sample_data
Config saved
[11/28/2024-19:50:37] Model init for dir C:\ProgramData\NVIDIA Corporation\chatrtx
19:50:37.240 > [PyE] [ChatRTXUIEngine] - INFO - ChatRTXUIEngine.py:122 - Application started with
19:50:37.241 > [PyE]  Dataset path : C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset
19:50:37.241 > [PyE]  App mode Mode.RAG
[11/28/2024-19:50:37] Application started with
 Dataset path : C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset
 App mode Mode.RAG
[11/28/2024-19:50:37] Model already downloaded
[11/28/2024-19:50:37] ChatRTX in Mode.RAG mode with datadir C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset
[11/28/2024-19:50:37] ChatRTX RAG mode initialized with model directory: C:\ProgramData\NVIDIA Corporation\chatrtx\models
19:50:37.242 > [PyE] 2024-11-28 19:50:37,240 - [ChatRTX] - INFO - backend.py:61 - Model already downloaded
19:50:37.243 > [PyE] 2024-11-28 19:50:37,241 - [ChatRTX] - INFO - backend.py:89 - ChatRTX in Mode.RAG mode with datadir C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset
19:50:37.243 > [PyE] 2024-11-28 19:50:37,241 - [ChatRTX] - INFO - chatrtx_rag.py:59 - ChatRTX RAG mode initialized with model directory: C:\ProgramData\NVIDIA Corporation\chatrtx\models
19:50:41.896 > [PyE] 2024-11-28 19:50:41,894 - [ChatRTX] - ERROR - chatrtx_rag.py:138 - Failed to set embedding model: Error Path C:\ProgramData\NVIDIA Corporation\chatrtx\models\multilingual-e5-base not found
19:50:41.896 > [PyE] Traceback (most recent call last):
19:50:41.897 > [PyE]   File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\ChatRTX\chatrtx_rag.py", line 134, in set_embedding_model
19:50:41.897 > [PyE]     self._embedding_model = HuggingFaceEmbedding(model_name=model_name)
19:50:41.898 > [PyE]   File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\llama_index\embeddings\huggingface\base.py", line 86, in __init__
19:50:41.898 > [PyE]     self._model = SentenceTransformer(
19:50:41.898 > [PyE]   File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 190, in __init__
19:50:41.899 > [PyE]     raise ValueError("Path {} not found".format(model_name_or_path))
19:50:41.899 > [PyE] ValueError: Path C:\ProgramData\NVIDIA Corporation\chatrtx\models\multilingual-e5-base not found
[11/28/2024-19:50:41] Failed to set embedding model: Error Path C:\ProgramData\NVIDIA Corporation\chatrtx\models\multilingual-e5-base not found
Traceback (most recent call last):
  File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\ChatRTX\chatrtx_rag.py", line 134, in set_embedding_model
    self._embedding_model = HuggingFaceEmbedding(model_name=model_name)
  File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\llama_index\embeddings\huggingface\base.py", line 86, in __init__
    self._model = SentenceTransformer(
  File "C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 190, in __init__
    raise ValueError("Path {} not found".format(model_name_or_path))
ValueError: Path C:\ProgramData\NVIDIA Corporation\chatrtx\models\multilingual-e5-base not found
19:50:42.479 > [PyE] C:\Users\Ryan\Desktop\ChatRTX\#Installed\env_nvd_rag\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
19:50:42.480 > [PyE]   warnings.warn(
19:50:45.538 > [PyE] 2024-11-28 19:50:45,538 - [ChatRTX] - INFO - chatrtx_rag.py:184 - Using the persisted value from C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset_vector_embedding
[11/28/2024-19:50:45] Using the persisted value from C:\ProgramData\NVIDIA Corporation\ChatRTX\sample_data\dataset_vector_embedding
19:50:45.792 > Logging inside listner  ON_PYTHON_ENGINE_INIT null
19:50:45.793 > In handle events
19:50:45.795 > Logging inside listner  ON_PYTHON_ENGINE_INIT null
19:50:45.796 > Logging inside listner  ON_PYTHON_ENGINE_INIT null
19:50:45.796 > Logging inside listner  ON_PYTHON_ENGINE_INIT null
19:50:45.797 > Logging inside listner  ON_PYTHON_ENGINE_INIT null
19:50:45.798 > getModelInfo call returned with value  {
  supported: [
    {
      name: 'Mistral 7B int4',
      id: 'mistral_7b_AWQ_int4_chat',
      ngc_model_name: 'nvidia/llama/mistral-7b-int4-chat:1.2',
      is_downloaded_required: true,
      downloaded: true,
      is_installation_required: true,
      setup_finished: true,
      min_gpu_memory: 8,
      should_show_in_UI: true,
      prerequisite: [Object],
      metadata: [Object],
      model_info: 'The Mistral-7B is a instruct fine-tuned text generation model',
      model_license: 'https://github.com/mistralai/mistral-src/blob/main/LICENSE',
      model_size: '4GB',
      modelDevelopers: 'Mistral AI',
      isTextBased: true,
      isImageBased: false,
      isChineseSupported: false,
      isEnglishSupported: true
    },
    {
      name: 'Llama2 13B int4',
      id: 'llama2_13b_AWQ_INT4_chat',
      ngc_model_name: 'nvidia/llama/llama2-13b:1.5',
      is_downloaded_required: true,
      downloaded: false,
      is_installation_required: true,
      setup_finished: false,
      min_gpu_memory: 16,
      should_show_in_UI: false,
      prerequisite: [Object],
      metadata: [Object],
      model_info: 'LlaMa 2 is a large language AI model capable of generating text and code in response to prompts',
      model_license: 'https://ai.meta.com/llama/license/',
      model_size: '6.8GB',
      modelDevelopers: 'Meta',
      isTextBased: true,
      isImageBased: false,
      isChineseSupported: false,
      isEnglishSupported: true
    },
    {
      name: 'ChatGLM 3 6B int4',
      id: 'chatglm3_6b_AWQ_int4',
      ngc_model_name: 'nvidia/chatglm3-6b-chat-int4:1.0',
      is_downloaded_required: true,
      downloaded: false,
      is_installation_required: true,
      setup_finished: false,
      min_gpu_memory: 8,
      should_show_in_UI: true,
      prerequisite: [Object],
      metadata: [Object],
      model_info: 'ChatGLM-6B is an open bilingual language model based on General Language Model framework, with 6.2 billion parameters',
      model_license: 'https://huggingface.co/THUDM/chatglm3-6b/blob/main/MODEL_LICENSE',
      model_size: '3.8GB',
      modelDevelopers: 'Zhipu AI',
      isTextBased: true,
      isImageBased: false,
      isChineseSupported: true,
      isEnglishSupported: false
    },
    {
      name: 'Gemma 7B int4',
      id: 'gemma_7b_int4',
      ngc_model_name: 'nvidia/llama/gemma-7b-int4-rtx:1.1',
      is_downloaded_required: true,
      downloaded: false,
      is_installation_required: true,
      setup_finished: false,
      min_gpu_memory: 16,
      should_show_in_UI: false,
      prerequisite: [Object],
      metadata: [Object],
      model_info: 'Gemma-7B is a 7B parameter model from Gemma family of models from Google',
      model_license: 'https://ai.google.dev/gemma/terms',
      model_size: '6.6GB',
      modelDevelopers: 'Google',
      isTextBased: true,
      isImageBased: false,
      isChineseSupported: false,
      isEnglishSupported: true
    },
    {
      name: 'CLIP',
      id: 'clip_model',
      hf_model_name: 'openai/clip-vit-large-patch14-336',
      is_downloaded_required: true,
      downloaded: false,
      download_link: 'https://huggingface.co/openai/clip-vit-large-patch14-336/resolve/main',
      is_installation_required: false,
      setup_finished: false,
      min_gpu_memory: 8,
      should_show_in_UI: true,
      prerequisite: [Object],
      metadata: {},
      model_info: 'CLIP is a multi-modal vision and language model used for image-text similarity and for zero-shot image classification',
      model_license: 'https://github.com/openai/CLIP/blob/main/LICENSE',
      model_size: '1.5GB',
      modelDevelopers: 'OpenAI',
      isTextBased: false,
      isImageBased: true,
      isChineseSupported: false,
      isEnglishSupported: true
    }
  ],
  selected: 'mistral_7b_AWQ_int4_chat',
  enable_asr: true,
  supported_asr: [
    {
      name: 'Whisper Medium Int8',
      installed: false,
      metadata: [Object]
    }
  ]
}
19:50:45.801 > Emiited here SUPPORTED_MODEL_UPDATE
19:50:45.801 > Emitted event via emit  SUPPORTED_MODEL_UPDATE
19:50:45.802 > Emitted event via emit  ACTIVE_MODEL_UPDATE
19:50:45.803 > getFineTuningInfo call returned with value
19:50:45.811 > getDatasetInfo call returned  {"sources": ["directory", "nodataset"], "selected": "directory", "path": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\dataset", "path_chinese": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\chinese_dataset", "path_clip": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\images_dataset", "selected_path": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\dataset"}
19:50:45.811 > getSampelQuestionInfo returned  {"default": {"modelIdList": ["mistral_7b_AWQ_int4_chat", "llama2_13b_AWQ_INT4_chat", "gemma_7b_int4"], "dataset_path": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\dataset", "isRelative": true, "queries": ["How does NVIDIA ACE generate emotional responses?", "What is Portal: Prelude RTX?"]}, "chinese": {"modelIdList": ["chatglm3_6b_AWQ_int4"], "dataset_path": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\chinese_dataset", "isRelative": true, "queries": ["NVIDIA ACE\u662f\u5982\u4f55\u751f\u6210\u5bcc\u6709\u60c5\u611f\u7684\u56de\u590d\u7684\uff1f", "\u4f20\u9001\u95e8\uff1a\u5e8f\u66f2 RTX \u7248\u662f\u4ec0\u4e48\uff1f"]}, "images": {"modelIdList": ["clip_model"], "dataset_path": "C:\\ProgramData\\NVIDIA Corporation\\ChatRTX\\sample_data\\images_dataset", "isRelative": true, "queries": ["Pictures of bicycles", "Pictures of toys", "Pictures of dinosaurs", "Pictures of computer"]}}
19:50:45.812 > call initChatbotEngine returned response  null

```

**Comment by Askovia** [comment]
I've slowly been doing troubleshooting tricks on this for my computer, and I found that by removing ctype from the requirements file will allow you to install the missing dependencies that it missed in the NVidia installer:

cd "C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0"
..\..\env_nvd_rag\Scripts\pip install -r requirements.txt

One I did this the error evolved into this one:

21:48:36.169 > systemLanguage
21:48:36.260 > Conda setup done!
21:48:36.341 > C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py
21:48:36.373 > Error while loading C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py *** PY *** Python Error  Call to 'fileImport' failed:
>         chatbot = await python(pyfile)
  at async initializeChatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:33:19)
  at async initializeBridgeCommands (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\index.js:21:18)

... across the bridge ...

  at exec_module (<frozen importlib._bootstrap_external>:883)
  at _call_with_frames_removed (<frozen importlib._bootstrap>:241)
> from backend import Backend, Mode
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\ChatRTXUIEngine.py:33)
> from ChatRTX.chatrtx import ChatRTX
  at <module> (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\engine\backend.py:2)
*** JS *** ModuleNotFoundError: No module named 'ChatRTX'
21:48:36.374 > Error while getting bridge commands TypeError: Cannot read properties of undefined (reading 'ChatBot')
    at new Chatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:79:27)
    at Chatbot.init (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar.unpacked\node_modules\pythonia\src\pythonia\Bridge.js:48:18)
    at initializeChatbot (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\chatbot\chatbot.js:227:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initializeBridgeCommands (C:\Program Files\NVIDIA Corporation\ChatRTX\RAG\trt-llm-rag-windows-ChatRTX_0.4.0\ChatRTXUI\dist\win-unpacked\resources\app.asar\build\bridge_commands\index.js:21:18)

**Comment by akaanupkumar** [comment]
Please try out the new 0.5 version ( link in readme and also available on NVIDIA App). Please let me know if anyone faces any such similar issues. If any issues seen on 0.5 version I will reopen this for investigation.

**Comment by ZombieWorm** [comment]
I am on the 0.5 version with my 5080. You have to run the exe from the folder win-unpacked not the one in \dist called "NVIDIA ChatRTX-0.0.1.exe" as you get the forever spinny thing.

**Comment by UPixelFoundry** [comment]
> Please try out the new 0.5 version ( link in readme and also available on NVIDIA App). Please let me know if anyone faces any such similar issues. If any issues seen on 0.5 version I will reopen this for investigation.

I'm still getting this with 0.5

**Comment by vilcapomaxlife** [comment]
Mine was suffering from this issue because my port 8000 was being used by another process in Windows called Incredibuild Manager. Make sure you have that port free, otherwise it will hang on you.
